---
- hosts: kubernetes_master
  become: yes
  tasks:
    - name: Install prerequisites
      yum:
        name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']
        state: present

    - name: Add Docker repo and install Docker
      shell: |
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        yum install -y docker-ce docker-ce-cli containerd.io

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Add Kubernetes repo
      yum_repository:
        name: kubernetes
        description: Kubernetes
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
        gpgcheck: yes
        state: present

    - name: Install Kubernetes tools
      yum:
        name: ['kubelet', 'kubeadm', 'kubectl']
        state: present

    - name: Enable kubelet
      service:
        name: kubelet
        state: started
        enabled: true

    - name: Initialize Kubernetes master
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_init

    - name: Set up kubeconfig for root user
      command: "mkdir -p $HOME/.kube && cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && chown $(id -u):$(id -g) $HOME/.kube/config"
      args:
        creates: "$HOME/.kube/config"

    - name: Install Flannel network plugin
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- hosts: kubernetes_slaves
  become: yes
  tasks:
    - name: Install prerequisites
      yum:
        name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']
        state: present

    - name: Add Docker repo and install Docker
      shell: |
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        yum install -y docker-ce docker-ce-cli containerd.io

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Add Kubernetes repo
      yum_repository:
        name: kubernetes
        description: Kubernetes
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
        gpgcheck: yes
        state: present

    - name: Install Kubernetes tools
      yum:
        name: ['kubelet', 'kubeadm']
        state: present

    - name: Enable kubelet
      service:
        name: kubelet
        state: started
        enabled: true

    - name: Join Kubernetes master (Replace with actual join command)
      command: "{{ hostvars['kubernetes_master']['kubeadm_init'].stdout_lines[-1] }}"